---
title: "Data Exploration"
author: "Mira Flynn"
date: "4/6/2022"
output: github_document
  toc: TRUE
---

```{r setup}
# Dependencies
library(tidyverse)
library(magrittr)
library(sf)

# Create the final PDF with code snippets shown
knitr::opts_chunk$set(echo = TRUE)

sf::sf_use_s2(FALSE) # this fixes the geometry of the shapefile for some reason


# This is a premade graph theme I originally got from ZDR and modified for myself
theme_common <- function() {
  theme_minimal() %+replace%
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(margin = margin(4, 4, 4, 4), size = 16),
    axis.title.y = element_text(margin = margin(4, 4, 4, 4), size = 16, angle = 90),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    strip.text.y = element_text(size = 12),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey90"),
    aspect.ratio = 10/16,
    plot.margin = unit(c(t = +0.5, b = +0, r = +0, l = +0), "cm"),
    plot.title = element_text(size = 18),
    # plot.title.position = "plot",
    plot.subtitle = element_text(size = 16),
    plot.caption = element_text(size = 12)
  )
}

```

```{r data-cleaning}
map = read_sf("data/LROC_GLOBAL_MARE_180.SHP") %>% # Load the maria shapefile
  st_make_valid() # I don't know what this does exactly but it fixes the shapefile
st_crs(map$geometry) <- 4326 # Again, I don't understand

df_craters <- read.csv("data/AstroStats_Robbins_Moon.csv") %>% # Load the dataset
  mutate( # Change longitude from 0 to 360  -> -180 to 180
      LON_ELLI_IMG = ifelse(LON_ELLI_IMG > 180, LON_ELLI_IMG-360, LON_ELLI_IMG)
  ) %>%
  filter(!is.na(LAT_ELLI_IMG)) %>% # Get rid of the 8 craters with NA ellipses
  st_as_sf( # Convert the craters dataset to a shapefile object
    coords = c("LON_ELLI_IMG", "LAT_ELLI_IMG"), 
    crs = st_crs(map),
    remove = FALSE
  ) %>% 
  mutate(
    intersection = geometry %>% st_intersects(map, sparse = TRUE),
    # Interesection column is where each point intersects the map, if any
    MARIA = (intersection %>% as.character()) != "integer(0)"
    # This is a bit chaotic. The intersection column is a funky object type, so
    # to compare it, I cast it to a character type. If the intersection is 0,
    # then the point is not in one of the maria regions. 
  ) %>%
  as.data.frame() %>% # Need to cast back to dataframe to get rid of geometry
  select( # Get rid of the intersection and geometry columns for clarity.
    -c(intersection, geometry)
  )

df_craters %>% write.csv(
    "data/AstroStats_Robbins_Moon_Maria.csv", 
    row.names = FALSE
  ) # Write modified data to CSV

df_craters %>% head()
```


```{r}
df_craters %>% summary()
```

```{r}
df_craters %>%
  ggplot(aes(x = LAT_ELLI_IMG, y = DIAM_ELLI_ANGLE_IMG)) +
  geom_point(alpha = 0.1) +
  geom_smooth()
```

```{r}
df_craters %>%
  ggplot(aes(x = LAT_ELLI_IMG, y = DIAM_ELLI_ECCEN_IMG)) +
  geom_point(alpha = 0.1) +
  geom_smooth()
```

```{r}
df_craters %>%
  ggplot(aes(x = LAT_ELLI_IMG, y = DIAM_ELLI_MAJOR_IMG)) +
  geom_point(alpha = 0.1) +
  geom_smooth() +
  scale_y_log10()
```


```{r}
df_craters %>%
  ggplot(aes(x = LAT_ELLI_IMG, y = DIAM_ELLI_MINOR_IMG)) +
  geom_point(alpha = 0.1) +
  geom_smooth() +
  scale_y_log10()
```


```{r}
df_craters %>%
  ggplot(aes(x = LON_ELLI_IMG, y = LAT_ELLI_IMG)) +
  geom_point(alpha = 0.1) +
  coord_fixed()

# WOAH THIS IS SO COOL LOOK AT THIS
# https://www.physics.unlv.edu/~jeffery/astro/moon/map/moon_map_mercator.jpg
```




```{r}
df_craters %>%
  ggplot(aes(LAT_ELLI_IMG)) +
  geom_histogram(bins = 36) +
  scale_x_continuous(breaks = c(-90,-60,-30,0,30,60,90))

# NOTE: This isn't accounting for diameter changes over latitudes
```


```{r}
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
# https://stackoverflow.com/questions/32370485/convert-radians-to-degree-degree-to-radians

# r = Radius of Moon in KM
r <- 1737.4
round_digits = 5

df_craters_hist <- df_craters %>%
  mutate(
    LAT_ROUND = round(LAT_ELLI_IMG/round_digits)*round_digits
  ) %>%
  filter(
    abs(LAT_ROUND) < 90
  ) %>%
  group_by(LAT_ROUND) %>%
  summarize(
    COUNT_LAT_ROUND = n()
  ) %>%
  mutate(
    NORM_LAT_ROUND = COUNT_LAT_ROUND/(2*pi*r*cos(deg2rad(LAT_ROUND)))
  )
df_craters_hist %>% head()
```



```{r}
df_craters_hist %>%
  ggplot(aes(x = LAT_ROUND, y = COUNT_LAT_ROUND)) +
  geom_col(
    aes(
      # fill = LAT_ROUND %>% as.character() %>% reorder(LAT_ROUND)
    ), 
    width = round_digits, 
    color = "black", 
    size = 1,
    show.legend = FALSE
  ) +
  scale_x_continuous(
    breaks = seq(-90,90,15),
    minor_breaks = seq(-90,90,5)
  ) +
  # scale_y_log10() +
  theme_common() +
  theme(
    panel.grid.major = element_line(color = "darkgrey"),
    panel.grid.minor = element_line(color = "grey90"),
  ) +
  labs(
    x = "Latitude (degrees)",
    y = "Craters"
  )
  
```

```{r}
df_craters_hist %>%
  ggplot(aes(x = LAT_ROUND, y = NORM_LAT_ROUND)) +
  geom_col(
    aes(
      # fill = LAT_ROUND %>% as.character() %>% reorder(LAT_ROUND)
    ), 
    width = round_digits, 
    color = "black", 
    size = 1,
    show.legend = FALSE
  ) +
  scale_x_continuous(
    breaks = seq(-90,90,15),
    minor_breaks = seq(-90,90,5)
  ) +
  # scale_y_log10() +
  theme_common() +
  theme(
    panel.grid.major = element_line(color = "darkgrey"),
    panel.grid.minor = element_line(color = "grey90"),
  ) +
  labs(
    x = "Latitude (degrees)",
    y = "Craters per Latitude Circumference \n (Craters/KM)"
  )
```



```{r}
df_craters %>%
  ggplot() +
  geom_point(
    aes(x = LON_ELLI_IMG, y = LAT_ELLI_IMG, color = MARIA), 
    size = 1,
    alpha = 0.2) +
  coord_fixed()


```



```{r}
# Create empty lists of lats and lons
lats = c()
lons = c()

# Add every combo of lats and lons, spaced at 2 degrees, to the list
for (lat in seq(-90,90,2)){
  for (lon in seq(-180,180,2)){
    lats = c(lats, lat)
    lons = c(lons, lon)
  }
}


pnts <- data.frame(lat = lats, lon = lons) %>% # Make a dataframe of the evenly
  # spaced points
  st_as_sf( # Then do the same things as we did with the craters dataset.
    coords = c("lon", "lat"), 
    crs = st_crs(map),
    remove = FALSE
  ) %>% 
  mutate(
    intersection = geometry %>% st_intersects(map) %>% as.integer(),
    # For some reason, this dataframe works a bit differently. I don't
    # understand why, and I'm not gonna spend a bunch of time figuring out why
    maria = !is.na(intersection)
  )

pnts %>% summary()
pnts %>%
  ggplot() +
  geom_point(aes(x = lon, y = lat, color = maria), size = 1) +
  coord_fixed()
```


```{r}
# Showing the original shapefile
map %>%
  ggplot() +
  geom_sf(
    fill = "blue",
    color = "blue"
    )
```



oh no there were so many links I used
https://wms.lroc.asu.edu/lroc/view_rdr/SHAPEFILE_LROC_GLOBAL_MARE
https://gis.stackexchange.com/questions/133625/checking-if-points-fall-within-polygon-shapefile
https://r-spatial.org/r/2017/03/19/invalid.html
https://gis.stackexchange.com/questions/413584/fix-features-with-invalid-spherical-geometry-polygon-shape-file-for-s2-geometr
https://stackoverflow.com/questions/54734771/sf-write-lat-long-from-geometry-into-separate-column-and-keep-id-column
https://stackoverflow.com/questions/54734771/sf-write-lat-long-from-geometry-into-separate-column-and-keep-id-column

